<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE note[
<!ELEMENT note (to, from, heading, (body|image), footer?)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT footer (#PCDATA)>
<!ELEMENT body (#PCDATA)>
<!ELEMENT image (#PCDATA)>
<!-- !ATTLIST body color ID #REQUIRES-->
<!--ATTLIST body saludo (hola|hi|konixhiwa)-->
<!ENTITY nbsp "&#xA0;">
<!ENTITY writer "Writer: Donald duck">
<!ENTITY copyright "Copyright: W3Schools">
]>
<note>
    <to>Tove</to>
    <from>Jani</from>
    <heading>Reminder</heading>
    <body>Don't forget me this weekend!</body>
</note>